### ISSUE TITLE
ParseException in junoEphemeris

### ISSUE THREAD

**Issue by wlwetzel** [daraghhollman/JUPT#35]
Attempting to run default_config.ini results in the error:
```
ValueError: 
Lon$_{III}$ ($^\circ}$)
             ^
ParseException: Expected end of text, found '$'  (at char 13), (line:1, col:14) 
```

Something strange to note is that this did not occur the first time I ran the default config, but has persisted even after a clean install of JUPT. 

Escaping the $ symbols as \\\$ seems to fix the issue.

**Comment by daraghhollman** [comment]
Hi again,

With some further testing, it seems the issue here is that there is a misplaced '}' after '\circ' resulting in the parse exception. This will be changed in a future commit.

With this fix, I was able to run the default config successfully. However, Python 3.12 might still have other issues yet to be found.
